// let's imagine this file is autogenerated from the backend
// ideally, we want to keep these api related types in sync
// with the backend instead of manually writing them out

export type BaseEntity = {
  id: string;
  createdAt: number;
};

export type Entity<T> = {
  [K in keyof T]: T[K];
} & BaseEntity;

export type Meta = {
  page: number;
  total: number;
  totalPages: number;
};

export type User = Entity<{
  firstName: string;
  lastName: string;
  email: string;
  role: "ADMIN" | "STUDENT" | "JURY";
  teamId: string;
  bio: string;
}>;

export type AuthResponse = {
  jwt: string;
  user: User;
};

export type Team = Entity<{
  name: string;
  description: string;
}>;

export type Discussion = Entity<{
  title: string;
  body: string;
  teamId: string;
  author: User;
  public: boolean;
}>;

export type Comment = Entity<{
  body: string;
  discussionId: string;
  author: User;
}>;

export type Event = Entity<{
  id: string;
  title: string;
  description: string;
  startDate: string;
  endDate: string;
  inscriptionDeadline: string;
  accessCode: string;
  isPublic: boolean;
  evaluationsStatus: "open" | "closed";
  createdAt: number;
}>;

export type Project = Entity<{
  id: string;
  eventId: string;
  courseId: string;
  name: string;
  description?: string;
  eventNumber?: string;
  logo: string;
  state: "UNDER_REVIEW" | "APPROVED" | "REJECTED";
  createdAt: number;
  updatedAt: number;

}>;

export type ProjectDocument = Entity<{
  id: string;
  projectId: string;
  url: string;
  createdAt: number;
  project: Project;
}>;

export type ProjectParticipant = Entity<{
  userId: string;
  projectId: string;
  studentCode?: string;
  project: Project;
}>;

export type ProjectAssignment = Entity<{
  projectId: string;
  memberUserId: string;
  memberEventId: string;
  memberRoleId: string;
  assigneAt: Date;
  updatedAt: Date;
  project: Project;
}>;

export type Course = Entity<{
  id: string;
  eventId: string;
  code: string;
  description?: string;
  active: boolean;
  createdAt: number;
}>;