// let's imagine this file is autogenerated from the backend
// ideally, we want to keep these api related types in sync
// with the backend instead of manually writing them out

import { user } from "@heroui/theme";
import { User } from "lucide-react";

export type BaseEntity = {
  id: string;
  createdAt: number;
};

export type Entity<T> = {
  [K in keyof T]: T[K];
} & BaseEntity;

export type Meta = {
  page: number;
  total: number;
  totalPages: number;
};

export type PlatformRole = {
  id: number;
  name: string;
  scope: string;
};

export type User = Entity<{
  firstName: string;
  lastName: string;
  email: string;
  phone?: string;
  active: boolean;
  status: string;
  platformRoles: PlatformRole[];
  platformPermissions: string[];
}>;

export type AuthResponse = {
  message: string;
};


export type Discussion = Entity<{
  title: string;
  body: string;
  teamId: string;
  author: User;
  public: boolean;
}>;

export type Comment = Entity<{
  body: string;
  discussionId: string;
  author: User;
}>;

export type EventMembership = Entity<{
  eventId: number;
  userId: number;
  eventRole: "STUDENT" | "JURY";
  event: Event;
}>;

export type Event = Entity<{
  id: number;
  name: string;
  description: string;
  startDate: string;
  endDate: string;
  inscriptionDeadline: string;
  accessCode: string;
  isPubliclyJoinable: boolean;
  evaluationsOpened: boolean;
  location?: string;
  status?: number;
  active: boolean;
  userEventRole?: "STUDENT" | "JURY";
  createdAt: number;
  updatedAt: number;
}>;

export type Project = Entity<{
  id: number;
  eventId: number;
  courseId: number;
  name: string;
  description?: string;
  eventNumber?: string;
  state: "UNDER_REVIEW" | "APPROVED" | "REJECTED";
  participants: ProjectParticipant[];
  documents: ProjectDocument[];
  jurorAssignments: ProjectAssignment[];
  createdAt: number;
  updatedAt: number;
}>;

export type ProjectDocument = Entity<{
  id: string;
  projectId: string;
  type: string;
  url: string;
  createdAt: number;
  project: Project;
}>;

export type ProjectParticipant = Entity<{
  firstName: string;
  lastName: string;
  email: string;
  projectId: string;
  studentCode?: string;
  project: Project;
}>;

export type ProjectAssignment = Entity<{
  projectId: string;
  memberEventId: string;
  assigneAt: Date;
  updatedAt: Date;
  project: Project;
}>;

export type Course = Entity<{
  id: number;
  eventId: number;
  code: string;
  description?: string;
  active: boolean;
  event?: { id: number; name: string };
  createdAt: number;
}>;

export type EvaluationScoreInput = {
  criterion: string;
  score: number;
};

export type Evaluation = Entity<{
  memberUserId: string;
  evaluatorId: string;
  grade: number;
  comments: string;
  scores: EvaluationScoreInput[];
}>;

export type Jury = Entity<{
  email: string;
  eventIds: number[];
  projectIds: number[];
  invitationStatus: "pending" | "accepted" | "declined";
}>;

export type Administrator = Entity<{
  email: string;
  invitationStatus: "pending" | "accepted" | "declined";
}>;

export type Criterion = Entity<{
  id: number;
  eventId: number;
  name: string;
  description: string;
  weight: number;
  criterionCourses: CriterionCourse[];
  createdAt: number;
}>;

export type CriterionCourse = Entity<{
  courseId: number;
  criterionId: number;
}>;
