// let's imagine this file is autogenerated from the backend
// ideally, we want to keep these api related types in sync
// with the backend instead of manually writing them out

export type BaseEntity = {
  id: string;
  createdAt: number;
};

export type Entity<T> = {
  [K in keyof T]: T[K];
} & BaseEntity;

export type Meta = {
  page: number;
  total: number;
  totalPages: number;
};

export type User = Entity<{
  firstName: string;
  lastName: string;
  email: string;
  role: "ADMIN" | "STUDENT" | "JURY";
  teamId: string;
  bio: string;
}>;

export type AuthResponse = {
  jwt: string;
  user: User;
};

export type Team = Entity<{
  name: string;
  description: string;
}>;

export type Discussion = Entity<{
  title: string;
  body: string;
  teamId: string;
  author: User;
  public: boolean;
}>;

export type Comment = Entity<{
  body: string;
  discussionId: string;
  author: User;
}>;

export type Event = Entity<{
  id: string;
  title: string;
  description: string;
  startDate: string;
  endDate: string;
  inscriptionDeadline: string;
  accessCode: string;
  isPublic: boolean;
  evaluationsStatus: "open" | "closed";
  createdAt: number;
}>;

export type ProjectPublic = Entity<{
  id: string;
  eventId: string;
  courseId: string;
  name: string;
  description?: string;
  eventNumber?: string;
  logo: string;
  state: "UNDER_REVIEW" | "APPROVED" | "REJECTED";
  participants: ProjectParticipant[];
  documents: ProjectDocument[];
  jurorAssignments: ProjectAssignment[];
  createdAt: number;
  updatedAt: number;

}>;

export type ProjectDocument = Entity<{
  id: string;
  projectId: string;
  type: string;
  url: string;
  createdAt: number;
  project: ProjectPublic;
}>;

export type ProjectParticipant = Entity<{
  firstName: string;
  lastName: string;
  email: string;
  projectId: string;
  studentCode?: string;
  project: ProjectPublic;
}>;

export type ProjectAssignment = Entity<{
  projectId: string;
  memberEventId: string;
  assigneAt: Date;
  updatedAt: Date;
  project: ProjectPublic;
}>;

export type CoursePublic = Entity<{
  id: string;
  eventId: string;
  code: string;
  description?: string;
  active: boolean;
  createdAt: number;
}>;
export type TeamMember = {
  name: string;
  photoUrl?: string;
};

export type Project = Entity<{
  title: string;
  description: string;
  eventId: string;
  teamId: string;
  isPublic: boolean;
  teamMembers: TeamMember[];
  documentsAttached: number;
  submittedAt: number | null;
  approvedAt: number | null;
}>;

export type Course = Entity<{
  code: string;
  description: string;
  events: { id: string; title: string }[];
  status: "active" | "inactive";
}>;

export type EvaluationDetail = Entity<{
  evaluationId: string;
  criterion: string;
  score: number;
}>;

export type EvaluationScoreInput = {
  criterion: string;
  score: number;
};

export type Evaluation = Entity<{
  memberUserId: string;
  evaluatorId: string;
  grade: number;
  comments: string;
  scores: EvaluationScoreInput[];
}>;

