import {
  Code,
  Cpu,
  Settings,
  Zap,
  BarChart,
  Calendar,
  HardHat,
  Dna,
} from 'lucide-react';
import type { Event, EngineeringField } from '../types';

export const events: Event[] = [
  {
    id: 1,
    name: 'Feria de Proyectos Finales 2025',
    date: '15 - 17 Mayo 2025',
    location: 'Campus Universidad del Norte',
    time: '9:00 AM - 6:00 PM',
    status: 'Inscripciones Abiertas',
    color: 'oklch(0.75 0.15 195)',
    gradient: 'from-cyan-500/20 via-blue-500/20 to-cyan-500/20',
    description: 'El evento principal de proyectos finales con las 6 ingenierías',
    slug: '/evento/feria-2025',
  },
  {
    id: 2,
    name: 'Hackathon Innovación Tech',
    date: '10 - 12 Junio 2025',
    location: 'Centro de Innovación UNINORTE',
    time: '48 horas continuas',
    status: 'Inscripciones Abiertas',
    color: 'oklch(0.82 0.18 330)',
    gradient: 'from-pink-500/20 via-rose-500/20 to-pink-500/20',
    description: 'Competencia intensiva de desarrollo e innovación tecnológica',
    slug: '/evento/hackathon-2025',
  },
  {
    id: 3,
    name: 'Simposio de Ingeniería Civil',
    date: '5 - 7 Julio 2025',
    location: 'Auditorio Principal',
    time: '8:00 AM - 5:00 PM',
    status: 'Inscripciones Abiertas',
    color: 'oklch(0.88 0.16 85)',
    gradient: 'from-yellow-500/20 via-orange-500/20 to-yellow-500/20',
    description: 'Presentaciones de proyectos de infraestructura sostenible',
    slug: '/evento/simposio-civil-2025',
  },
];

export const engineeringFields: EngineeringField[] = [
  {
    id: 1,
    name: 'Ingeniería de Sistemas y Computación',
    icon: Code,
    color: 'oklch(0.75 0.15 195)',
    description: 'Innovación en software, IA y sistemas computacionales',
    gradient: 'from-cyan-500/20 to-blue-500/20',
  },
  {
    id: 2,
    name: 'Ingeniería Civil',
    icon: HardHat,
    color: 'oklch(0.82 0.18 330)',
    description: 'Construcción sostenible e infraestructura inteligente',
    gradient: 'from-pink-500/20 to-rose-500/20',
  },
  {
    id: 3,
    name: 'Ingeniería Mecánica',
    icon: Settings,
    color: 'oklch(0.88 0.16 85)',
    description: 'Diseño mecánico avanzado y automatización',
    gradient: 'from-yellow-500/20 to-orange-500/20',
  },
  {
    id: 4,
    name: 'Ingeniería Eléctrica',
    icon: Zap,
    color: 'oklch(0.7 0.2 280)',
    description: 'Sistemas de potencia y energías renovables',
    gradient: 'from-purple-500/20 to-violet-500/20',
  },
  {
    id: 5,
    name: 'Ingeniería Electrónica',
    icon: Cpu,
    color: 'oklch(0.78 0.17 160)',
    description: 'Circuitos avanzados y sistemas embebidos',
    gradient: 'from-green-500/20 to-emerald-500/20',
  },
  {
    id: 6,
    name: 'Ingeniería Industrial',
    icon: BarChart,
    color: 'oklch(0.85 0.15 50)',
    description: 'Optimización de procesos y gestión de operaciones',
    gradient: 'from-amber-500/20 to-yellow-500/20',
  },
  {
    id: 7,
    name: 'Ingeniería Biomédica',
    icon: Dna,
    color: 'oklch(0.72 0.19 15)',
    description: 'Tecnología médica y dispositivos para el cuidado de la salud',
    gradient: 'from-red-500/20 to-pink-500/20',
  },
];

export { Calendar };
